name: Build WASM and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure Git for repository access
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/" || true
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt, clippy
        
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
    - name: Run Rust tests
      run: cargo test
      
    - name: Run Rust clippy
      run: cargo clippy -- -D warnings
      
    - name: Check Rust formatting
      run: cargo fmt --check
      
    - name: Build WASM package for web
      run: wasm-pack build --target web --out-dir html/pkg --dev --features wasm
      
    - name: Create Pages deployment directory
      run: |
        mkdir -p pages-deploy
        
    - name: Copy HTML files to deployment directory
      run: |
        cp -r html/* pages-deploy/
        touch pages-deploy/.nojekyll
        echo "Deployed file structure:"
        find pages-deploy -type f | head -20
    
    - name: Replace GitHub repository placeholder
      run: |
        sed -i "s|\${GITHUB_REPOSITORY}|${{ github.repository }}|g" pages-deploy/index.html
        
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './pages-deploy'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4